In [1]:
import pandas as pd

listings = pd.read_csv("../data/raw/listings.csv.gz")
print(listings.shape)
listings.head()

(15134, 90)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,25358481,https://www.airbnb.com/rooms/25358481,20260922161635,2026-09-24,NaN,*The Athens Green Apt*,Modern 🎨 Cozy 25 sq.m. ground floor flat🌼Fully...,NaN,https://a0.muscache.com/pictures/a354ac74-4bb7...,434487,...,4.99,4.76,4.86,00000109380,NaN,2,2,0,0,4.52
1,27262,https://www.airbnb.com/rooms/27262,20260922161635,2026-09-24,previous scrape,"AQA-No7, Great mattress, high speed internet",THE MATTRESS - KING KOIL - Camden Luxury 160x2...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,37177,...,4.97,4.75,4.71,00002433111,NaN,1,1,0,0,0.17
2,33945,https://www.airbnb.com/rooms/33945,20260922161635,2026-09-24,NaN,Spacious Cosy aprtm very close to Metro!,Apartment located near metro station. Safe nei...,NaN,https://a0.muscache.com/pictures/1a7a1026-f5f1...,146553,...,4.91,4.65,4.81,00000874421,NaN,1,1,0,0,0.47
3,49489,https://www.airbnb.com/rooms/49489,20260922161635,2026-09-24,previous scrape,44 Ermou st - 3bdr apt in the heart of Athens,"Fully furnished, 98 sq.mt., apartment on 44 Er...",NaN,https://a0.muscache.com/pictures/9640239/4bfd2...,225612,...,4.87,4.89,4.69,00000876484,NaN,3,3,0,0,0.77
4,60394,https://www.airbnb.com/rooms/60394,20260922161635,2026-09-24,NaN,Cosy apartment! Great central Athens location!,Fully furnished cozy apartment in the best nei...,NaN,https://a0.muscache.com/pictures/477282/db550f...,290864,...,4.97,4.92,4.92,00000508830,NaN,1,1,0,0,0.28

In [2]:
listings.columns.tolist()

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'source',
 'name',
 'description',
 'neighborhood_overview',
 'picture_url',
 'host_id',
 'host_url',
 'host_profile_id',
 'host_profile_url',
 'host_name',
 'host_since',
 'hosts_time_as_user_years',
 'hosts_time_as_user_months',
 'hosts_time_as_host_years',
 'hosts_time_as_host_months',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bathrooms_text',
 'bedrooms',
 'beds',
 'amenities',
 'price',
 'price_quote_checkin_date',
 'price_quote_checkout_date',
 'price_quote_total_price',
 'price_quote_price_per_night',
 'price_quote_raw',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'availability_eoy',
 'number_of_reviews_ly',
 'estimated_occupancy_l365d',
 'estimated_revenue_l365d',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'license',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month']

In [3]:
listings["price"].head(10)

0     $60.00
1        NaN
2     $57.25
3        NaN
4     $78.50
5        NaN
6    $106.00
7        NaN
8     $60.00
9    $451.00
Name: price, dtype: str

In [4]:
print(listings[["price", "bedrooms", "review_scores_rating"]].isna().mean())
listings["price"].head(10)

price                   0.060790
bedrooms                0.000264
review_scores_rating    0.131162
dtype: float64

0     $60.00
1        NaN
2     $57.25
3        NaN
4     $78.50
5        NaN
6    $106.00
7        NaN
8     $60.00
9    $451.00
Name: price, dtype: str

In [5]:
print(listings.shape)

(15134, 90)

In [6]:
# 1. Μετατροπή τιμής από κείμενο σε αριθμό
listings["price_num"] = (
    listings["price"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)

# 2. Περιγραφικά στατιστικά
print(listings["price_num"].describe())

# 3. Ακραίες τιμές
print(listings["price_num"].quantile([0.01, 0.05, 0.5, 0.95, 0.99]))

count    14214.000000
mean       153.762784
std        476.874954
min         12.590000
25%         81.600000
50%        112.000000
75%        160.075000
max      45647.500000
Name: price_num, dtype: float64
0.01     36.0000
0.05     53.5325
0.50    112.0000
0.95    334.5840
0.99    672.8739
Name: price_num, dtype: float64

In [7]:
listings["price"].dropna().head(10).tolist()

['$60.00',
 '$57.25',
 '$78.50',
 '$106.00',
 '$60.00',
 '$451.00',
 '$62.20',
 '$110.67',
 '$130.50',
 '$159.50']

In [8]:
listings["price"].dropna().head(10).tolist()

['$60.00',
 '$57.25',
 '$78.50',
 '$106.00',
 '$60.00',
 '$451.00',
 '$62.20',
 '$110.67',
 '$130.50',
 '$159.50']

In [9]:
listings["price"].dropna().str[0].value_counts()

price
$    14214
Name: count, dtype: int64

In [10]:
listings["price_num"].median()

np.float64(112.0)

In [11]:
listings["price_num"] = (
    listings["price"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)

print(listings.shape)
print(listings["price_num"].describe())
print(listings["price_num"].quantile([0.01, 0.05, 0.5, 0.95, 0.99]))

(15134, 91)
count    14214.000000
mean       153.762784
std        476.874954
min         12.590000
25%         81.600000
50%        112.000000
75%        160.075000
max      45647.500000
Name: price_num, dtype: float64
0.01     36.0000
0.05     53.5325
0.50    112.0000
0.95    334.5840
0.99    672.8739
Name: price_num, dtype: float64

In [12]:
df = listings.dropna(subset=["price_num"]).copy()

low, high = df["price_num"].quantile([0.01, 0.99])
df = df[(df["price_num"] >= low) & (df["price_num"] <= high)]

print(df.shape)
print(df["price_num"].describe())

(13939, 91)
count    13939.000000
mean       136.073702
std         85.987718
min         36.000000
25%         82.000000
50%        112.000000
75%        159.000000
max        672.030000
Name: price_num, dtype: float64

In [13]:
listings.nlargest(10, "price_num")[["name", "room_type", "accommodates", "price_num"]]

,name,room_type,accommodates,price_num
6587,96 apartment,Entire home/apt,5,45647.50
11594,Ησυχο διαμέρισμα πολύ κοντά στο μετρο Λαρίσης,Entire home/apt,3,11918.00
44,Colourful Cosmopolitan Athens | Acropolis view,Entire home/apt,2,11699.67
5609,Harmony Haven,Entire home/apt,2,11490.00
2076,Private Grey and White Room,Private room,2,10338.00
11535,Ήσυχο στούντιο κοντά στο μετρό σταθμού Λαρίσης,Entire home/apt,3,9176.86
5914,Ermou Funky Loft_1,Entire home/apt,2,8509.15
5928,Ermou Funky Loft_2,Entire home/apt,2,8509.15
5929,Ermou Funky Loft_3,Entire home/apt,2,8509.15
5930,Ermou Funky Loft_4,Entire home/apt,2,8509.15

In [15]:
from pathlib import Path

Path("../data/processed").mkdir(parents=True, exist_ok=True)
df.to_parquet("../data/processed/listings_clean.parquet", index=False)

In [16]:
print(df["room_type"].value_counts())
print(df.groupby("room_type")["price_num"].median())

top_hoods = (
    df.groupby("neighbourhood_cleansed")["price_num"]
    .agg(["count", "median"])
    .sort_values("count", ascending=False)
    .head(15)
)
print(top_hoods)

room_type
Entire home/apt    12984
Private room         848
Hotel room           100
Shared room            7
Name: count, dtype: int64
room_type
Entire home/apt    112.0
Hotel room         262.0
Private room       104.0
Shared room         39.0
Name: price_num, dtype: float64
                                  count   median
neighbourhood_cleansed
ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ             3085  137.000
ΚΟΥΚΑΚΙ-ΜΑΚΡΥΓΙΑΝΝΗ                1301  137.000
ΜΟΥΣΕΙΟ-ΕΞΑΡΧΕΙΑ-ΝΕΑΠΟΛΗ           1027  103.330
ΝΕΟΣ ΚΟΣΜΟΣ                         977  108.000
ΑΓΙΟΣ ΚΩΝΣΤΑΝΤΙΝΟΣ-ΠΛΑΤΕΙΑ ΒΑΘΗΣ    928   90.425
ΠΑΓΚΡΑΤΙ                            535  102.500
ΠΛΑΤΕΙΑ ΑΤΤΙΚΗΣ                     483   84.000
ΘΗΣΕΙΟ                              477  129.500
ΚΟΛΩΝΑΚΙ                            454  143.500
ΠΕΤΡΑΛΩΝΑ                           435  104.000
ΑΜΠΕΛΟΚΗΠΟΙ                         426   94.165
ΑΚΡΟΠΟΛΗ                            416  151.825
ΚΕΡΑΜΕΙΚΟΣ                          411  114.000
ΓΟΥΔΙ                               261  104.000
ΚΥΨΕΛΗ                              241   82.500

In [17]:
cols = [
    "accommodates", "bedrooms", "beds", "bathrooms_text", "bathrooms",
    "latitude", "longitude", "review_scores_rating", "review_scores_location",
    "number_of_reviews", "minimum_nights", "availability_365",
    "host_is_superhost", "instant_bookable", "amenities",
]
cols = [c for c in cols if c in df.columns]
print(df[cols].isna().mean().round(3))
print(df[cols].dtypes)

accommodates              0.000
bedrooms                  0.000
beds                      0.016
bathrooms_text            0.000
bathrooms                 1.000
latitude                  0.000
longitude                 0.000
review_scores_rating      0.124
review_scores_location    0.124
number_of_reviews         0.000
minimum_nights            0.000
availability_365          0.000
host_is_superhost         0.000
instant_bookable          1.000
amenities                 0.000
dtype: float64
accommodates                int64
bedrooms                  float64
beds                      float64
bathrooms_text                str
bathrooms                 float64
latitude                  float64
longitude                 float64
review_scores_rating      float64
review_scores_location    float64
number_of_reviews           int64
minimum_nights            float64
availability_365            int64
host_is_superhost             str
instant_bookable          float64
amenities                     str
dtype: object

In [ ]:
print(df["host_is_superhost"].value_counts(dropna=False))
print(df["bathrooms_text"].value_counts().head(10))

In [18]:
df = df[df["room_type"].isin(["Entire home/apt", "Private room"])].copy()
print(df.shape)
df.to_csv("../data/processed/listings_clean.csv", index=False)

(13832, 91)

In [19]:
print(df["host_is_superhost"].value_counts(dropna=False))
print(df["bathrooms_text"].value_counts().head(10))

host_is_superhost
t    7055
f    6777
Name: count, dtype: int64
bathrooms_text
1 bath              10392
2 baths              1336
1.5 baths             867
1 private bath        525
3 baths               172
2.5 baths             161
1 shared bath         125
1.5 shared baths       50
4 baths                41
3.5 baths              37
Name: count, dtype: int64

In [20]:
import json, re
import numpy as np

# 1. Μπάνια από το κείμενο
def parse_baths(text):
    if pd.isna(text):
        return np.nan
    t = str(text).lower()
    m = re.search(r"(\d+(\.\d+)?)", t)
    if m:
        return float(m.group(1))
    return 0.5 if "half" in t else np.nan

df["baths"] = df["bathrooms_text"].apply(parse_baths)
df["shared_bath"] = df["bathrooms_text"].str.contains("shared", case=False, na=False).astype(int)

# 2. Superhost και κριτικές
df["is_superhost"] = df["host_is_superhost"].map({"t": 1, "f": 0})
df["has_reviews"] = (df["number_of_reviews"] > 0).astype(int)

# 3. Ανέσεις
def parse_amenities(s):
    try:
        return [a.lower() for a in json.loads(s)]
    except Exception:
        return []

df["amenity_list"] = df["amenities"].apply(parse_amenities)
df["n_amenities"] = df["amenity_list"].apply(len)

flags = {
    "has_wifi": "wifi",
    "has_ac": "air conditioning",
    "has_kitchen": "kitchen",
    "has_balcony": "balcony",
    "has_elevator": "elevator",
    "has_parking": "parking",
}
for col, kw in flags.items():
    df[col] = df["amenity_list"].apply(lambda L: int(any(kw in a for a in L)))

# 4. Απόσταση από το Σύνταγμα (km)
def haversine_km(lat1, lon1, lat2, lon2):
    R = 6371
    p1, p2 = np.radians(lat1), np.radians(lat2)
    dphi = p2 - p1
    dl = np.radians(lon2 - lon1)
    a = np.sin(dphi / 2) ** 2 + np.cos(p1) * np.cos(p2) * np.sin(dl / 2) ** 2
    return 2 * R * np.arcsin(np.sqrt(a))

df["dist_center_km"] = haversine_km(df["latitude"], df["longitude"], 37.9755, 23.7348)

df[["baths", "is_superhost", "n_amenities", "has_ac", "dist_center_km"]].describe()

              baths  is_superhost   n_amenities        has_ac  dist_center_km
count  13830.000000  13832.000000  13832.000000  13832.000000    13832.000000
mean       1.200940      0.510049     35.582490      0.815645        1.603137
std        0.638542      0.499917     12.783458      0.387788        0.905081
min        0.000000      0.000000      0.000000      0.000000        0.025948
25%        1.000000      0.000000     27.000000      1.000000        0.978260
50%        1.000000      1.000000     37.000000      1.000000        1.440721
75%        1.000000      1.000000     45.000000      1.000000        2.054287
max       50.000000      1.000000     89.000000      1.000000        6.122485

In [21]:
print(df["baths"].value_counts().sort_index())
df[df["baths"] > 4][["name", "accommodates", "bedrooms", "bathrooms_text", "baths"]]

baths
0.0        32
0.5        18
1.0     11042
1.5       917
2.0      1354
2.5       164
3.0       198
3.5        41
4.0        42
4.5         7
5.0         8
5.5         1
6.0         3
7.0         2
50.0        1
Name: count, dtype: int64

,name,accommodates,bedrooms,bathrooms_text,baths
746,VILLA AMARYLLIS Keramikos,10,5.0,4.5 baths,4.5
1122,Elegant 5bm-5ba Apt/Acropolis View/Ideal Location,13,5.0,5 baths,5.0
1225,"Artistic rooms near Acropolis, with prvt. baths",13,6.0,6 baths,6.0
1697,Stylish 5bd-5ba Apt/Acropolis View/Ideal Location,13,5.0,5 baths,5.0
1709,Troon of Athens,14,5.0,5 baths,5.0
2214,Bauhaus Building 330sq. Sleeps 24 persons,16,10.0,4.5 baths,4.5
2655,Spacious 7bd-7ba apt/Huge Roof Top-Unique Views!,14,7.0,7 baths,7.0
3668,Modern & Spacious Apartment Ideal for Groups,8,4.0,4.5 baths,4.5
5834,Real City Suites Syntagma,2,7.0,7 baths,7.0
5944,Gracious Accessible 4Bd/5Ba Apt in Ideal Location,13,4.0,5 baths,5.0
6770,Luxury 4Bdrm Penthouse near Acropolis,8,4.0,4.5 baths,4.5
7019,En Plaka - Athens Elegant Estate,7,4.0,4.5 baths,4.5
10019,Acropolis Soul,8,4.0,4.5 baths,4.5
10195,One Paradise MAX 29 Guests (747),16,6.0,4.5 baths,4.5
10701,Athens Residences Near Acropolis up to 18ppl!,16,6.0,6 baths,6.0
11772,Historical 9 bedrooms building,16,9.0,6 baths,6.0
11832,Once & Forever Estate,16,7.0,5.5 baths,5.5
12569,Huge House • Walk to Acropolis • KASO Homes,16,6.0,5 baths,5.0
12748,Odeon Hotel: Single Room,2,50.0,50 baths,50.0
13363,Omian Sapphire Residence | Group Stay & Rooftop,12,5.0,5 baths,5.0
14538,The old merchant's house,8,4.0,5 baths,5.0
15084,One Bldg – 4 Unique Apts – Green Rooftop! EP9 ...,14,6.0,5 baths,5.0

In [22]:
df["baths"] = df["baths"].clip(upper=5)

In [23]:
print(df["baths"].value_counts().sort_index())
df[df["baths"] > 4][["name", "accommodates", "bedrooms", "bathrooms_text", "baths"]]

baths
0.0       32
0.5       18
1.0    11042
1.5      917
2.0     1354
2.5      164
3.0      198
3.5       41
4.0       42
4.5        7
5.0       15
Name: count, dtype: int64

,name,accommodates,bedrooms,bathrooms_text,baths
746,VILLA AMARYLLIS Keramikos,10,5.0,4.5 baths,4.5
1122,Elegant 5bm-5ba Apt/Acropolis View/Ideal Location,13,5.0,5 baths,5.0
1225,"Artistic rooms near Acropolis, with prvt. baths",13,6.0,6 baths,5.0
1697,Stylish 5bd-5ba Apt/Acropolis View/Ideal Location,13,5.0,5 baths,5.0
1709,Troon of Athens,14,5.0,5 baths,5.0
2214,Bauhaus Building 330sq. Sleeps 24 persons,16,10.0,4.5 baths,4.5
2655,Spacious 7bd-7ba apt/Huge Roof Top-Unique Views!,14,7.0,7 baths,5.0
3668,Modern & Spacious Apartment Ideal for Groups,8,4.0,4.5 baths,4.5
5834,Real City Suites Syntagma,2,7.0,7 baths,5.0
5944,Gracious Accessible 4Bd/5Ba Apt in Ideal Location,13,4.0,5 baths,5.0
6770,Luxury 4Bdrm Penthouse near Acropolis,8,4.0,4.5 baths,4.5
7019,En Plaka - Athens Elegant Estate,7,4.0,4.5 baths,4.5
10019,Acropolis Soul,8,4.0,4.5 baths,4.5
10195,One Paradise MAX 29 Guests (747),16,6.0,4.5 baths,4.5
10701,Athens Residences Near Acropolis up to 18ppl!,16,6.0,6 baths,5.0
11772,Historical 9 bedrooms building,16,9.0,6 baths,5.0
11832,Once & Forever Estate,16,7.0,5.5 baths,5.0
12569,Huge House • Walk to Acropolis • KASO Homes,16,6.0,5 baths,5.0
12748,Odeon Hotel: Single Room,2,50.0,50 baths,5.0
13363,Omian Sapphire Residence | Group Stay & Rooftop,12,5.0,5 baths,5.0
14538,The old merchant's house,8,4.0,5 baths,5.0
15084,One Bldg – 4 Unique Apts – Green Rooftop! EP9 ...,14,6.0,5 baths,5.0

In [24]:
print((df["baths"] == 0).sum())

32

In [25]:
df.drop(columns=["amenity_list"]).to_csv("../data/processed/listings_features.csv", index=False)

In [26]:
print(df.loc[df["baths"] == 0, "bathrooms_text"].value_counts())

bathrooms_text
0 baths           22
0 shared baths    10
Name: count, dtype: int64

In [27]:
df["baths"] = df["baths"].clip(upper=5)
df.drop(columns=["amenity_list"]).to_csv("../data/processed/listings_features.csv", index=False)
print(df.shape)

(13832, 104)